services:
  - type: web
    name: vibe-finops-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: SNOWFLAKE_USER
        sync: false
      - key: SNOWFLAKE_PASSWORD
        sync: false
      - key: SNOWFLAKE_ACCOUNT
        sync: false
      - key: SNOWFLAKE_DATABASE
        sync: false
      - key: SNOWFLAKE_SCHEMA
        sync: false
      - key: SNOWFLAKE_WAREHOUSE
        sync: false
    autoDeploy: true
